### ISSUE TITLE
Seprate nodes for read and write

### ISSUE THREAD

**Issue by sdarshil** [Altinity/clickhouse-operator#1000]
i am trying to optimize my clickhouse architecture and i was thinking that what if i use two replicas insted of one in my clickhouse cluster and the use one clickhouse replica for select queries only and use one replica for insert queries only !
will it improvise my architecture for more speed in the frontend microservice as it just uses only select queries ??

current architecture:
One clickhouse node with one zookeeper with clickhouse-operator from altinity
tables are created with replicatedmergetree() as in future we are willing to add replicas to our clickhousecluster !
no distributed are being used as suggested by the altinity team as we dont have terrabytes of data getting inserted .

**Comment by alex-zaitsev** [comment]
You may use one replica for writes and another one for reads, but you will loose HA in this case. Use replicaServiceTemplate in order to have a dedicated service:
https://github.com/Altinity/clickhouse-operator/blob/d7e654a341e4102038f6226febc338b8060c64dd/docs/chi-examples/99-clickhouseinstallation-max.yaml#L218
