### ISSUE TITLE
Disable table propagation to new shards

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#1020]
We use `/docker-entrypoint-initdb.d` (https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh#L107) to initialize our shards and I'm wondering if it's possible to disable the table propagation for a given CHI? thanks!

**Comment by UnamedRus** [comment]
I think we need to have 3 options for schema:

1. Propagate everything (table & databases)
2. Propagate databases (for Replicated database engine)
2. Disable propagation

**Comment by alex-zaitsev** [comment]
Hi @a-dot , version 0.19 and above has a special setting to disable schema propagation: https://github.com/Altinity/clickhouse-operator/blob/145b1d329c2d1ab1726b654e211b8f44ba2e1c62/deploy/operator/parts/crd.yaml#L672

Set it to None in order to disable, like this: https://github.com/Altinity/clickhouse-operator/blob/145b1d329c2d1ab1726b654e211b8f44ba2e1c62/docs/chi-examples/99-clickhouseinstallation-max.yaml#L168

**Comment by a-dot** [comment]
That's great! I'll close the issue now! Thanks!
