### ISSUE TITLE
Finalizer & namespace deletion issue

### ISSUE THREAD

**Issue by guidoiaquinti** [Altinity/clickhouse-operator#1043]
Deleting the namespace without having deleted first the `chi-` resources will make the delete command hang indefinitely.

Tested on `0.18.4`.

**Comment by Slach** [comment]
it will happens if clickhouse-operator install in the same namespace with `chi`
and you have situation when finalizer deleted before custom resource

use separate namespace for installation `clickhouse-operator` 
if you install in kube-system, then operator will watch all namespaces for `chi` reconciling
in other case specify `watchNamespaces` in custom `chopconf` resource for customizing clickhouse-operator settings

look `kubectl explain chopconf` for details
