### ISSUE TITLE
"Recreate" update strategy

### ISSUE THREAD

**Issue by dheerajathrey** [Altinity/clickhouse-operator#1120]
Is there a way to recreate all clickhouse pods at the same time instead of the current RollingUpdate strategy whenever there are changes. It is taking a very long time for all pods to restart with RollingUpdate.

In case of rollingupdate, is there an option to set maxSurge?

**Comment by UnamedRus** [comment]
Can you check this pr https://github.com/Altinity/clickhouse-operator/pull/1124?

It should solve your problem.

**Comment by alex-zaitsev** [comment]
@dheerajathrey 

Since 0.22 the default strategy for big clusters is the following:
1. Upgrade (re-create) the first shard  (one replica in a time)
2. The upgrade 50% of remaining shards in parallel (one replica in a time), maximum in 5 parallel threads.
3. Then upgrade the remaining cluster (one replica in a time), maximum in 5 parallel threads.

This can be changed/tuned in operator configuration, see there: https://github.com/Altinity/clickhouse-operator/blob/221d151a80e57f02ca4a1a421ff3698294553426/config/config.yaml#L207
