### ISSUE TITLE
Operator gets stuck when deleting the installation on kubernetes

### ISSUE THREAD

**Issue by Sephirus** [Altinity/clickhouse-operator#1142]
Hey guys,

I'm have some issues configuring my clickhouse instances on kubernetes. I've set my operator when I apply it it goes perfectly fine and everything is created with success. But when I try to delete the installation (`kubectl delete -n dev-clickhouse  -f .\clickhouse-operator.yaml`) it gets stuck somewhere:

![image](https://user-images.githubusercontent.com/53007859/230357074-5ef532f8-2016-4d21-8410-6e5d6bd4e527.png)

Even though everything seems deleted on the cluster it sure ain't because if I try to run again the installation, the operator as before runs smoothly but when i try to apply my clickhouse server instance I get an error:

![image](https://user-images.githubusercontent.com/53007859/230357695-25583573-bb3a-4e90-b2ae-16a27c25d1d9.png)

I've checked my CRDs, but there's nothing there regarding the operator installation and I've even tried to run `kubectl patch crd/clickhouseinstallationtemplates.clickhouse.altinity.com -p '{"metadata":{"finalizers":[]}}' --type=merge` to see if there was any finalizer stuck but it says that there is no changes. I've also tried deleting the namespace but I still get the same problem as expected.

Any help would be gladly appreciated.

Thanks in advance,
Filipe

**Comment by mmangione** [comment]
I can't believe this is still an issue. This has been HOURS in the process of researching for me. I finally found the solution in a different problem answer. You need to do the following:

```
To solve this problem if you failed and deleted the CRD (thanks to! @hodgesrm)

There's a problem with stuck finalizers that can cause old CHI installations to hang. The sequence of operations looks like this.

You delete the existing ClickHouse operator using kubectl delete -f operator-installation.yaml with running CHI clusters.
You then drop the namespace where the CHI clusters are running, e.g., kubectl delete ns my-namespace
This hangs. You run kubectl get ns my-namespace -o yaml and you'll see a message like the following:
'message': Some content in the namespace has finalizers remaining: finalizer.clickhouseinstallation.altinity.com

That means the CHI can't be deleted because its finalizer was deleted out from under it.

The fix is to figure out the chi name which should still be visible and edit it to remove the finalizer reference.

kubectl -n my-namespace get chi
kubectl -n my-namespace edit clickhouseinstallations.clickhouse.altinity.com my-clickhouse-cluster
Remove the finalizer from the spec, save it, and everything will delete properly.
```

I didn't have CHI, but I was able to get this to work by running
`kubectl -n my-namespace edit clickhouseinstallations.clickhouse.altinity.com`
and deleting the line under finalizers.

Clickhouse team, please fix this.

**Comment by mmangione** [comment]
Hi @denisok,

Thanks for responding so quickly. In my case, this was bundled with [SigNoz](https://github.com/SigNoz/signoz). I installed everything into the same namespace, and this hang occurred when attempting to delete the namespace. 

Initially, I thought I had to give the process time to finish, so I had to start rotating and installing things into new namespaces. I soon had a dozen hanging namespaces at the same point. These namespaces didn't have anything associated with them at all. All of the resources had been purged except the ClickHouse Operator, which caused the namespace deletion to hang in the "Terminating" state indefinitely.

For the sake of this conversation, I just ran with a default helm installation of SigNoz into a namespace called `testchi`.

`kubectl create ns testchi`
`helm --namespace testchi install signoz signoz/signoz`

After waiting for all of the pods to successfully start up, I tore down the whole namespace:
`kubectl delete ns testchi`

The namespace perpetually hangs in the "Terminating" state again.

Running the command:
`kubectl api-resources --verbs=list --namespaced -o name \\n  | xargs -n 1 kubectl get --show-kind --ignore-not-found -n testchi`

Returns the output:
```
NAME                                                               CLUSTERS   HOSTS   STATUS      HOSTS-COMPLETED   AGE
clickhouseinstallation.clickhouse.altinity.com/signoz-clickhouse   1          1       Completed                     11m20s
```

This is the state it will stay stuck in indefinitely. The finalizer never finalizes and holds the namespace deletion inappropriately indefinitely.

If I edit the namespace resource, I see the following information:
```
apiVersion: v1
kind: Namespace
metadata:
  name: testchi
  uid: 8ddb5974-7eeb-4131-b960-09bd6bc1dad4
  resourceVersion: '166103303'
  creationTimestamp: '2023-08-10T18:07:19Z'
  deletionTimestamp: '2023-08-10T18:10:12Z'
  labels:
    kubernetes.io/metadata.name: testchi
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2023-08-10T18:07:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:kubernetes.io/metadata.name: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-08-10T18:10:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"NamespaceContentRemaining"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"NamespaceDeletionContentFailure"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"NamespaceDeletionDiscoveryFailure"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"NamespaceDeletionGroupVersionParsingFailure"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"NamespaceFinalizersRemaining"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
      subresource: status
  selfLink: /api/v1/namespaces/testchi
status:
  phase: Terminating
  conditions:
    - type: NamespaceDeletionDiscoveryFailure
      status: 'False'
      lastTransitionTime: '2023-08-10T18:10:19Z'
      reason: ResourcesDiscovered
      message: All resources successfully discovered
    - type: NamespaceDeletionGroupVersionParsingFailure
      status: 'False'
      lastTransitionTime: '2023-08-10T18:10:19Z'
      reason: ParsedGroupVersions
      message: All legacy kube types successfully parsed
    - type: NamespaceDeletionContentFailure
      status: 'False'
      lastTransitionTime: '2023-08-10T18:10:19Z'
      reason: ContentDeleted
      message: All content successfully deleted, may be waiting on finalization
    - type: NamespaceContentRemaining
      status: 'True'
      lastTransitionTime: '2023-08-10T18:10:19Z'
      reason: SomeResourcesRemain
      message: >-
        Some resources are remaining:
        clickhouseinstallations.clickhouse.altinity.com has 1 resource instances
    - type: NamespaceFinalizersRemaining
      status: 'True'
      lastTransitionTime: '2023-08-10T18:10:19Z'
      reason: SomeFinalizersRemain
      message: >-
        Some content in the namespace has finalizers remaining:
        finalizer.clickhouseinstallation.altinity.com in 1 resource instances
spec:
  finalizers:
    - kubernetes
```

The way to fix this issue is to run:
`kubectl -n my-namespace edit clickhouseinstallations.clickhouse.altinity.com`

And simply delete the 2 lines under the finalizers sections. The namespace then successfully terminates.

**Comment by denisok** [comment]
Hi @mmangione,

so as I understand it SigNoz chart has [ClickHouse](https://github.com/SigNoz/charts/blob/main/charts/signoz/Chart.yaml#L22) as the dependency that installs the operator and creates a cluster.

I think what you would like to do is to do `helm uninstall` because there are too many dependencies and I suppose that command should delete all resources in the right order, so you wouldn't have CHI cluster that would exist. After that, you can delete the namespace.
There are still some caveats: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

Please also check the namespace where CHI resource was created and operator deployment is running.

I don't see so far an issue with the operator or its resources. During deletion of the namespace, you probably terminate the controller (chi operator deployment) and still have CHI cluster that depends on it so it leaves that finalizer hanging forever.

So either deploy the operator in a different namespace and CHI cluster in another (which is unsupported by SigNoz helm), or delete CHI deployments first - either by `kubectl delete` of `helm uninstall` before deleting the namespace.

Thanks,
Denys

**Comment by mmangione** [comment]
Hi @denisok,

Thanks for your suggestion. I tried both of those and they both resulted the same hanging process. Exact same messages and everything. Is there somewhere I can see what the finalizer is waiting on?

Thank you,
Micah

**Comment by pishangujeniya** [comment]
Thanks @mmangione  [You helped](https://github.com/Altinity/clickhouse-operator/issues/1142#issuecomment-1673695814) me a lot, I have been trying to fix this deletion of namespace due to SigNoz since last 6 hours.

**Comment by prashant-shahi** [comment]
@pishangujeniya Maintainer of SigNoz here 👋 

To cleanly uninstall SigNoz and signoz–managed ClickHouse:

```bash
helm -n platform uninstall "my-release"

kubectl -n platform patch \
  clickhouseinstallations.clickhouse.altinity.com/my-release-clickhouse \
  -p '{"metadata":{"finalizers":[]}}' --type=merge
```

Detailed instructions can be found here: https://signoz.io/docs/operate/kubernetes/#uninstall-signoz-cluster
