### ISSUE TITLE
ClickHouse Automatic Replication

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [Altinity/clickhouse-operator#1475]
If i have a 3 shard 3 replica setup of clickhouse pods deployed in k8s cluster, and i see that the distribution of my pod is uneven across the availability zones (1 in zone-a, 4 in zone-b, 4 in zone-c) due to my misconfiguration of clickhouse operator config "maxPodsPerNode". Now, if i delete the PVC of any 2 replicas in each shard and ensure that only one replica in each shard is available - and if i redeploy clickhouse - will it automatically cascade the data from that available shard to the new replicas eventually ? Is it a right approach to proceed ?

**Comment by Slach** [comment]
instead of deleting PVC

better scale down cluster with change `kind: ClickHouseInstallation` (chi) manifest
and delete PVC if you have `Retain` storage policy

thereafter, rollback wrong operator configand apply `podAntiAffinity` to `chi.spec` if necessary

then scale out cluster with changing `chi` resource again
