### ISSUE TITLE
Metrics fetches never timeout

### ISSUE THREAD

**Issue by kcking** [Altinity/clickhouse-operator#154]
Hello all. 

We have found an issue in our cluster where the operator metric fetch loop can get stuck waiting for a DB Ping or Exec that will never time out. I believe this can be solved by using `PingContext` and `ExecContext` inside of `clickhouse.go`, and passing in a `context.Context` with a reasonable timeout -- maybe something like 10 seconds.

What do you folks think? Thanks for the awesome operator!

**Comment by sunsingerus** [comment]
Yes, sure we need to introduce some kind of timeout for SQL processor, which runs queries towards ClickHouse instances in Pods. So far this part (monitoring in general and SQL queries in particular) is done in simple and straightforward manner, mainly because there are were plenty of other thing to look after, and in order to have monitoring "operational in general".

**Comment by filimonov** [comment]
@kcking sounds reasonable. can you prepare the PR with that change?

**Comment by kcking** [comment]
just added a PR!
