### ISSUE TITLE
single transient failure stops metrics fetcher

### ISSUE THREAD

**Issue by kcking** [Altinity/clickhouse-operator#160]
right now a single failure to fetch metrics from any chi pod will stop all fetching of metrics for that installation, until it is updated or the ch-operator pod is rolled.

Instead, some more resilient error handling should be done so that a single transient failure doesnt stop all metric collection

**Comment by sunsingerus** [comment]
>right now a single failure to fetch metrics from any chi pod will stop all fetching of metrics for that installation

In case metrics exporter fails to collect metrics from a ClickHouse host, this host is considered to be dead and is excluded from list of hosts to collect metrics from. Not the whole `ClickHouseInstallation`, but one host only. This approach do have its flaws, of course.

>some more resilient error handling should be done so that a single transient failure doesnt stop all metric collection

Yes, sure, we need to be more precise.
Right now, metrics exporter is being extracted from operator into separate binary and this will provide good starting point for more intellectual monitoring.

**Comment by kcking** [comment]
Thank you for the reply. In looking through the code, it looks like the entire installation is removed according to this line: https://github.com/Altinity/clickhouse-operator/blob/master/pkg/apis/metrics/exporter.go#L107

That is interesting that you are splitting out the exporter. Will it be included as another container alongside each `clickhouse-server` container? I'd be curious to hear about the timeline you have in mind for that, if you are able to share.

Metrics staying reliable is very important to us, and I'd be happy to help make it more resilient.

**Comment by sunsingerus** [comment]
> ...it looks like the entire installation is removed...

Yes, you are right, sorry for confusion, it is just intention (not implemented yet) to clear not the whole `ClickHouseInstallation` from being monitored, but one host only. Thanks for pointing this out again!

> ...splitting out the exporter. Will it be included as another container alongside each `clickhouse-server` container?

Current intention is no extract monitor from `clickhouse-operator` container and provide two separate binaries in two separate containers within one **clickhouse-operator** Pod:
1. `clickhouse-operator`
1. `metrics-exporter`

This is expected to provide more responsibility separation and ways to develop different exporters (say not only into Prometheus, but other systems as well) without touching main operator.
This code is in [0.6.0 branch](https://github.com/Altinity/clickhouse-operator/tree/0.6.0) already. There is two entry points in `cmd` folder - `cmd/metrics_exporter` and `cmd/operator` for two binaries. Branch 0.6.0  is planned to be released soon, there will be no more active features development for 0.6.0, but some housekeeping, like writing docs, examples, etc

As to providing some king of monitoring container alongside ClickHouse instance - like to launch ClickHouse Pod with two containers:
1. ClickHouse
1. ClickHouse monitor

this is in TODO list also, but no clear timeline for this yet. We plan to develop some kind of monitor/health-checker in order to be able to monitor more complex ClickHouse health/status checks than simple `is ClickHouse running or not?` by checking HTTP request/reply.

> Metrics staying reliable is very important to us, and I'd be happy to help make it more resilient.

Thanks a lot! It would be nice if you can share your ideas or best practices or whatever experience you have with ClickHouse in Kubernetes to make the whole project better. I'd be glad to discuss any ideas/propositions/feature requests or anything else. Good feature requests can drive development onto proper path. Good Pull Requests are even better :)

**Comment by alex-zaitsev** [comment]
Fixed in 0.8.0. 

Now failures do not stop monitoring anymore. Also two more generic metrics were added:
chi_clickhouse_metric_fetches
chi_clickhouse_metric_fetch_errors

In case of fetch failures the latter one is 1.

There are also other stability enhancements related to monitoring. 
You can check 0.8.0 branch and 'dev' tag for dockerhub image.
