### ISSUE TITLE
What are all these configuration directories for?

### ISSUE THREAD

**Issue by MatthiasLohr** [Altinity/clickhouse-operator#262]
Hey,

I have a question regarding the bunch of volumes/ConfigMaps mounted into the container. What are all these different config directories defined in the [Deployment](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1618) for, why do they need to be mounted by the operator and how is the influence to the actual ClickHouse pods spawned by the operator?

| **Mount Path** | **Mount Name** | **ConfigMap Name** |
| --- | --- | --- |
| `/etc/clickhouse-operator` | `etc-clickhouse-operator-folder` | [`etc-clickhouse-operator-files`](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1294) |
| `/etc/clickhouse-operator/conf.d` | `etc-clickhouse-operator-confd-folder` | [`etc-clickhouse-operator-confd-files`](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1407) |
| `/etc/clickhouse-operator/config.d` | `etc-clickhouse-operator-configd-folder` | [`etc-clickhouse-operator-configd-files`](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1422) |
| `/etc/clickhouse-operator/templates.d` | `etc-clickhouse-operator-templatesd-folder` | [`etc-clickhouse-operator-templatesd-files`](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1468) |
| `/etc/clickhouse-operator/users.d` | `etc-clickhouse-operator-usersd-folder` | [`etc-clickhouse-operator-usersd-files`](https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1567) |

I couldn't find any documentation how these are handled by the operator.

  * operator-files -- ok, seems to be the basic configuration of the operator
  * confd-files -- is empty? Why do we need it then?
  * configd-files  - What's this? Is this configuration copied to all clickhouse instances? What is the difference to confd-files?
  * Seems to contain templates for `ClickHouseInstallationTemplate`, but what is `ClickHouseInstallationTemplate` any why do I need that? Is a  `ClickHouseInstallation` resource not enough for starting Clickhouse?
  * usersd-files -- Why do we need that? Why is it not included in configd-files?

Best regards and thanks in advance
Matthias

**Comment by sunsingerus** [comment]
All these features are for advanced configuration and not required for basic use-cases.
Please, take a look into [available examples](https://github.com/Altinity/clickhouse-operator/tree/master/docs/chi-examples) Lots of different cases are fully covered by examples provided.

**Comment by sunsingerus** [comment]
I'll try to write detailed explanation on what is for what in near future.

**Comment by sunsingerus** [comment]
One more thing - all these parts are related to **operator's functionality** and are not required to be dealt with by ClickHouse operators. So, this area is of interest to operator's developers. If you want to add new functionality to operator, please share your ideas. If you\d like to `use operator`, there are little chances you'll ever need to dive into all these things at all.

**Comment by MatthiasLohr** [comment]
Thank you for your replies. Right now, I'm trying to create a Helm Chart for the operator, so I need to understand what can be configured, what does the operator need to work and what can I offer for Helm Chart users for configuration. That's quite difficult when having no real documentation available.

The Helm Chart will be - once it's in a semi-usable state - open source (Apache 2.0 License), so it would be nice if you could help me understanding how the operator works and how it treats the configurations provided in the different files/directories.

**Comment by sunsingerus** [comment]
Ok, I see the point. From Helm Chart developer's point of view, more internal details are required indeed. Let me see what we can do

**Comment by mr-yaky** [comment]
@MatthiasLohr do you have some parts already developed ? I'm also interesting on this. Will be really nice to have it on upstream also. So, may be you can prepare it like PR.

**Comment by MatthiasLohr** [comment]
There is some (non-working) stuff in a (currently) private project on GitLab. I'm still missing the documentation I need to have to get the operator running and - major point - configurable by a helm chart. Since, at least when I was last active on this, there was no additional documentation, I had no chance of providing something useful. Maybe, if the documentation situation is improved or I have some oracles helping me how the operator works, I would be happy to proceed/share my current results.

**Comment by sunsingerus** [comment]
since this topic is gaining some traction, let's reopen discussion

>operator-files -- ok, seems to be the basic configuration of the operator

Yes, it is the place where config files for operator itself are kept. Operator reads its `config.yaml`, reads its `clickhouseoperatorconfigurations.clickhouse.altinity.com` CR and merges final config out of all available config parts.

>    confd-files -- is empty? Why do we need it then?

It is the place where ClickHouse configuration files unique for each instance (host) within CHI are located. It is empty, because in default operator installation no such files are provided. Yes, we do need it,


> configd-files - What's this? Is this configuration copied to all clickhouse instances? What is the difference to confd-files?

It is the place where ClickHouse configuration files common for all instances within CHI are located. It is not copied to all instances, but mounted to all instances as one ConfigMap read-by-everyone

> Seems to contain templates for ClickHouseInstallationTemplate, but what is ClickHouseInstallationTemplate any why do I need that? Is a ClickHouseInstallation resource not enough for starting Clickhouse?

`ClickHouseInstallationTemplate` is a template, which can be used to bootstrap `ClickHouseInstallation`. One `ClickHouseInstallation` can be bootstrapped with ordered set of `ClickHouseInstallationTemplate`(s). `ClickHouseInstallationTemplate` is an optional resource, used for advanced setups. It is not required for basic cluster.

> usersd-files -- Why do we need that? Why is it not included in configd-files?

This is the place where ClickHouse configuration files with users settings are located. Files are common for all instances within CHI. Is is convenient to separate users setup from other options.

@MatthiasLohr feel free to share your helm chart, so everybody could take a look. I'd propose to make a PR with what you already have into ClickHouse operator repo and continue with unified efforts.

**Comment by sunsingerus** [comment]
Discussion moved into https://github.com/Altinity/clickhouse-operator/pull/358
