### ISSUE TITLE
ability to change dns domain name

### ISSUE THREAD

**Issue by f41gh7** [Altinity/clickhouse-operator#332]
With custom domain name (not cluster.local), i`ve got errors and operator cannot connect to pods.
```bash
connection.go:54] FAILED Ping(http://***:***@chi-clickhouse-dev-replicas-only-0-0.dev.svc.cluster.local:8123/) dial tcp: lookup chi-clickhouse-dev-replicas-only-0-0.dev.svc.cluster.local on 10.200.0.3:53: no such host
```
and more errors like that.

 As far as i see, it`s part of const template at
https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/namer.go#L125

 I guess, it`s possible to move dns domain into template as well. Or probably, some workaround exists?

**Comment by f41gh7** [comment]
ahh, found issue with same problem.

**Comment by lololozhkin** [comment]
@f41gh7, could you please provide link to this similar issue? 
Our clickhouse operator pod cannot scrape metrics from ch pods, because of name resolution, we use custom domain (instead of cluster.local). We cannot find issues about that, and cannot find any ability configure this behaviour :( 
As you mentioned, we also found, that `.cluster.local` part is hardcoded...
