### ISSUE TITLE
 The operator whether to support concurrent creating clickhouse pod? 

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#376]

**Comment by SalleryWang** [comment]
![image](https://user-images.githubusercontent.com/45587738/81394230-36bf2b80-9154-11ea-9abe-77196ca13665.png)

i will test！

**Comment by SalleryWang** [comment]
i think the clickhouse pod can be parallel， isn‘t it？

**Comment by SalleryWang** [comment]
if it works，i will commit，hahah

**Comment by alex-zaitsev** [comment]
Hi @SalleryWang , since operator creates one pod per stateful set, podmanagementpolicy setting does not make any sense. The sequence is controlled by an operator. Currently, it is concurrent between different ClickHouse installations, but sequential in scope of one installation. We do not plan to make it concurrent in scope of one installation at this moment.

**Comment by SalleryWang** [comment]
what can i do？ it is too slow for me if i create many shards




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/10/2020 01:20, alex-zaitsev wrote:

Hi @SalleryWang , since operator creates one pod per stateful set, podmanagementpolicy setting does not make any sense. The sequence is controlled by an operator. Currently, it is concurrent between different ClickHouse installations, but sequential in scope of one installation. We do not plan to make it concurrent in scope of one installation at this moment.

**Comment by alex-zaitsev** [comment]
@SalleryWang, how many shards do you need to create? Usually, the first shard takes long because it needs to pull the image, and others are fast.

**Comment by SalleryWang** [comment]
about 100




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/12/2020 06:29, alex-zaitsev wrote:

@SalleryWang, how many shards do you need to create? Usually, the first shard takes long because it needs to pull the image, and others are fast.

**Comment by SalleryWang** [comment]
it takes long time on pv




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

在2020年05月12日 09:44，SalleryWang 写道：
about 100




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/12/2020 06:29, alex-zaitsev wrote:

@SalleryWang, how many shards do you need to create? Usually, the first shard takes long because it needs to pull the image, and others are fast.

**Comment by alex-zaitsev** [comment]
That's a lot. We need to consider parallelisation for such clusters. 

What is your volumeBindingMode for the storage class? Maybe you can change it to Immediate to speed things up a bit.

**Comment by SalleryWang** [comment]
aws




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/13/2020 15:48, alex-zaitsev wrote:

That's a lot. We need to consider parallelisation for such clusters.

What is your volumeBindingMode for the storage class? Maybe you can change it to Immediate to speed things up a bit.

**Comment by alex-zaitsev** [comment]
Supported since 0.22.x
