### ISSUE TITLE
operator is not creating sts and pods

### ISSUE THREAD

**Issue by leoxhj** [Altinity/clickhouse-operator#657]
Dear team,
We have found opeartor isn't creating sts, and pods if `operator` and `clickhouse cluster` deployed in different namespaces.
Let's say operator has deployed in ns: `clickhouse-system`, and clusters have been deployed in ns: `clickhouse`, the result is we only see the chi is successfully created, but no sts, and pods, there's also no any logs came up if we check in operator pod.

But weird thing is  if we deploy operator to default ns: `kube-system`, then it is fine for cluster in other namespaces.

could you please kindly confirm whether this is opeartor issues?

Thanks and Best Regards,
Leo

**Comment by Slach** [comment]
this is expected behavior, by default if clickhouse-operator installed on `kube-system` it will watch all namespaces for CRD
if operator install in other namespace, it look only current namespace

also, behavior is defined on
/etc/clickhouse-operator/config.yaml
on Watch Namespaces Section - `watchNamespaces` setting 
```
################################################
##
## Watch Namespaces Section
##
################################################

# List of namespaces where clickhouse-operator watches for events.
# Concurrently running operators should watch on different namespaces
watchNamespaces:
  - your-namespace
```

you can edit `/etc/clickhouse-operator/config.yaml` it via edit ConfigMap `etc-clickhouse-operator-files` in same namespace where clickhouse-operator was installed

https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml#L1479-L1497
