### ISSUE TITLE
Unable to restart CHI when changing global configuration stored in the operator

### ISSUE THREAD

**Issue by marcioapm** [Altinity/clickhouse-operator#733]
There is no way to apply a configuration change to the CHI if this configuration is in the operator's `users.d` folder.
CHI itself is not restartable, and the operator won't pick up the change and apply it to the CHIs, even after having been restarted.

I added a new file (a new profile) to the operator's `users.d` config-map, and there was no obvious way to get that applied to my previously created CHI.

Deleting and re-Creating the CHI worked as expected.
Maybe I am doing something wrong?

operator version is 0.14 using yandex 21.6.5 image.

**Comment by alex-zaitsev** [comment]
@marcioapm , could you be more specific, please? What configuration change you can not apply?

**Comment by marcioapm** [comment]
> @marcioapm , could you be more specific, please? What configuration change you can not apply?

Updated my OP.

**Comment by alex-zaitsev** [comment]
@marcioapm , If you modify operator configuration, you can restart operator and it will apply the change.

However, why are you adding a new profile via operator configuration instead of adding it to the CHI itself? CHI has 'profiles' section or you can supply config files directly using 'files' section. See different examples here: https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-016-settings-04.yaml

**Comment by marcioapm** [comment]
Got it. Thanks!
