### ISSUE TITLE
<remote_servers> Add user and password authentication

### ISSUE THREAD

**Issue by czhfe** [Altinity/clickhouse-operator#797]
<remote_servers> Add user and password authentication

**Comment by alex-zaitsev** [comment]
> > [#265 (comment)](https://github.com/Altinity/clickhouse-operator/issues/265#issuecomment-948361288) Using `secret` tag is better than changing the user and password of `remote_servers`.
> 
> What should I do when deploying clickhouse using clickhouse-operator?

```
    settings:
      remote_servers/default/secret: abcd
```

'default' is a cluster name in this example. We can probably generate secret randomly when CHI is created, not sure if it makes sense. @yuzhichang , what do you think?

You can also use from_env in order to store the password in environment vars. See https://github.com/Altinity/clickhouse-operator/issues/700

**Comment by yuzhichang** [comment]
@alex-zaitsev The `secret` value doesn't matter. The value just shall not be empty string.
[ckman](https://github.com/housepower/ckman/) enforces non-empty password of user `default`, and use `secret` (if cluster >=v20.10.3.30+) or `user` and `password` (if cluster <v20.10.3.30).

**Comment by R-omk** [comment]
> We can probably generate secret randomly when CHI is created

This would be great, but only generate a new secret if no existing one is explicitly specified.

**Comment by alex-zaitsev** [comment]
Fully implemented in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.20.0
