### ISSUE TITLE
About Restart RollingUpdate

### ISSUE THREAD

**Issue by su-houzhen** [Altinity/clickhouse-operator#853]
I am using clickhouse-operator 0.16.0 for test. And I got a question during the test.

Prerequisite: My CHI is set spec.restart = RestartRollingUpdate
Operation: restart operator
Result: The ClickHouse cluster is restarted.

at the same time:
Prerequisite: My CHI no longer sets spec.restart = RestartRollingUpdate
Operation: restart operator
Result: The ClickHouse cluster was not restarted.

According to the description of restart, I think even if RestartRollingUpdate is set, restarting the operator should not cause the clickhouse cluster to restart.

Is this a bug? Or my understanding of the setting is wrong. 
Looking forward to your reply, Thanks.

**Comment by Slach** [comment]
yep, spec.restart = RollingUpdate mean `restart each server explicitly during rolling update`, and contsant have not mental name

This is a 'soft restart' button. When set to 'RollingUpdate' operator will restart ClickHouse pods in a graceful way. Remove it after the use in order to avoid unneeded restarts.

**Comment by sunsingerus** [comment]
please check [this reply](https://github.com/Altinity/clickhouse-operator/issues/855#issuecomment-1015374266) as well
