### ISSUE TITLE
Automatic recovery after complete data loss

### ISSUE THREAD

**Issue by R-omk** [Altinity/clickhouse-operator#969]
The algorithm for manual recovery has already been described here 
https://kb.altinity.com/altinity-kb-setup-and-maintenance/recovery-after-complete-data-loss/

**Expected behavior**

- delete pvc  and delete pod/statfulset    (or any other or any other way to delete all data from volume )
- after new pod starts, the recovery process will immediately begin

**Comment by R-omk** [comment]
At the moment I see that the operator creates databases (atomic engine too) and even distributed tables, but not ReplicatedMergeTree tables:

```
<Error> executeQuery: Code: 253. DB::Exception: Replica /clickhouse/tables/8b70dd70-8114-4237-8bdf-120fceb06ed0/shard0/replicas/chi-XXXX-s0r0 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.6.5 (official build))
```



Also the operator does not restore the statefulset
https://github.com/Altinity/clickhouse-operator/issues/970

**Comment by R-omk** [comment]
related https://github.com/Altinity/clickhouse-operator/issues/857

**Comment by mlucic** [comment]
Seeing the same issue on my end. Database is created on the new instance but the table (ReplicatedMergeTree) is not, and the logs contain the same DB::Exception REPLICA_IS_ALREADY_EXIST

**Comment by mlucic** [comment]
1. I created ClickHouseInstallation with 1 shard, 3 replicas, pointing to 3 ClickHouse Keeper nodes
2. I created the database and table as follows:

 `
 CREATE DATABASE testdb ON CLUSTER '{cluster}'
 
 CREATE TABLE IF NOT EXISTS testdb.testtable ON CLUSTER '{cluster}'
(
    id UUID,
    timestamp DateTime
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/opalogs', '{replica}')
PARTITION BY toYYYYMM(timestamp)
ORDER BY (id, timestamp);
`

3. I reduced the replicas on the ClickHouseInstallation to 2
4. After the third replica was removed I increased replicas back to 3

I expected that the new third replica would successfully have created the database and table, however only the database was created successfully. The table failed to create due to the REPLICA_IS_ALREADY_EXIST error.

Here is the complete log from the new third replica:
[chi-di-clickhouse-installation-replicated-0-2-0.log](https://github.com/Altinity/clickhouse-operator/files/9105184/chi-di-clickhouse-installation-replicated-0-2-0.log)

**Comment by Slach** [comment]
@mlucic which clickhouse-operator version do you use?

**Comment by mlucic** [comment]
> @mlucic which clickhouse-operator version do you use?

0.18.5

**Comment by R-omk** [comment]
> REPLICA_IS_ALREADY_EXIST

operator version 0.19.0

**Comment by mlucic** [comment]
> > REPLICA_IS_ALREADY_EXIST
> 
> operator version 0.19.0

I just upgraded to 0.19.0, can confirm that this issue is still present

**Comment by alex-zaitsev** [comment]
@R-omk, restore process after loosing PV or PVC is fully implemented in 0.23.x

**Comment by R-omk** [comment]
> @R-omk, restore process after loosing PV or PVC is fully implemented in 0.23.x

operator (0.23.3)  
-cannot  detect sts remove and recreate  
-cannot  detect sts wrong scale (zero ) and restore scale

**Comment by Slach** [comment]
@devalexops could you share `clickhouse-operator` container logs after deletion PV/PVC/Pod?

**Comment by devalexops** [comment]
@Slach I don't have any past logs, but if I deleted a pod now I see the following logs:

```
I0627 14:24:48.502850       1 worker.go:275] processReconcilePod():clickhouse/chi-clickhouse-stage-stage-0-2-0:Delete Pod. clickhouse/chi-clickhouse-stage-stage-0-2-0
I0627 14:24:49.192718       1 worker.go:266] processReconcilePod():clickhouse/chi-clickhouse-stage-stage-0-2-0:Add Pod. clickhouse/chi-clickhouse-stage-stage-0-2-0
I0627 14:25:11.545629       1 chi.go:38] prepareListOfTemplates():clickhouse/clickhouse-stage:Found applicable templates num: 0
I0627 14:25:11.545684       1 chi.go:82] ApplyCHITemplates():clickhouse/clickhouse-stage:Applied templates num: 0
I0627 14:25:11.675948       1 chi.go:38] prepareListOfTemplates():clickhouse/clickhouse-stage:Found applicable templates num: 0
I0627 14:25:11.675974       1 chi.go:82] ApplyCHITemplates():clickhouse/clickhouse-stage:Applied templates num: 0
I0627 14:25:11.700101       1 worker.go:387] clickhouse/clickhouse-stage/80e49753-3c5f-422b-a078-6424b09bdd47:updating endpoints for CHI-1 clickhouse-stage
I0627 14:25:11.753384       1 worker.go:389] clickhouse/clickhouse-stage/80e49753-3c5f-422b-a078-6424b09bdd47:IPs of the CHI-1 update endpoints clickhouse/clickhouse-stage: len: 3 [10.4.3.108 10.4.2.120 10.4.8.57]
I0627 14:25:11.802623       1 chi.go:38] prepareListOfTemplates():clickhouse/clickhouse-stage:Found applicable templates num: 0
I0627 14:25:11.802707       1 chi.go:82] ApplyCHITemplates():clickhouse/clickhouse-stage:Applied templates num: 0
```

**Comment by Slach** [comment]
is your 
```
spec:
  volumeClaimTemplates:
    - name: your-name
      reclaimPolicy: Retain
```
?

**Comment by devalexops** [comment]
@Slach yes, but as I mentioned I have deleted PV for that 3 replica manually.
I basically just try to understand how operator restores failed replicas or syncs new replica into the cluster.

**Comment by Slach** [comment]
> I have deleted PV for that 3 replica manually.

Do you mean you completely deleted the whole cluster/shard with data without any live replica?
In this case no way to restore data
only backups

**Comment by devalexops** [comment]
@Slach nope
I had cluster with 3 replicas.
I deleted 1 replica completely (pod, PVC, PV)
Operator recreated that replica, but didn't create database/tables.

**Comment by Slach** [comment]
it was -0-0-0 pod?

**Comment by devalexops** [comment]
Nope, 0-2-0

**Comment by dbazhal** [comment]
same here. operator 0.24.0 clickhouse 23.8.
1 shard, 3 replicas, I intentionally delete a pod and a pvc (0-0-0).

1) pod and pvc are recreated, and is stuck in DB::Exception: Database NAME_WAS_HERE does not exist. (UNKNOWN_DATABASE).
2) when i create the database, nothing happens(schema and tables are not synced from other replicas)
3) if i then remove the statefulset (0-0-0), it is not recreated
4) when the operator is restarted, the sts is created back again, but still no recovery happens.

should we /reopen this? reportedly the issue is not fixed, it's easy to reproduce.

**Comment by augustodsgv** [comment]
Hello! I had the same issue as @dbazhal, and restarting the operator worked indeed (thanks btw), so it seems like this is an issue with the operator reconciliation. I'm using version 0.24.0 of the operator, is it still an issue with more recent versions of the operator or has it been patched?
